# Generated by Django 3.1.6 on 2021-02-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='maintext',
            field=models.TextField(default='lorem ipsum', max_length=2000),
        ),
        migrations.AlterField(
            model_name='texts',
            name='searchtext',
            field=models.TextField(default='d', max_length=60),
        ),
    ]
